-- Align the persisted schema with fields used by the admin CRUD forms.
ALTER TABLE projects ADD COLUMN IF NOT EXISTS category TEXT;

ALTER TABLE skills ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'General';
ALTER TABLE skills ADD COLUMN IF NOT EXISTS icon TEXT DEFAULT '⭐';
ALTER TABLE skills ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#6B7280';
ALTER TABLE skills ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;

ALTER TABLE education ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'education';
ALTER TABLE experience ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'professional';
